changed vector base to allow leg backward movement
alexandrelafleur/Tetrabot pull request #80
Opened 2020-03-10 14:25 UTC by turcottep

y movement is now positive towards the ground

2020-03-10 14:27 UTC, turcottep commented
@alexandrelafleur how do you add the do not merge tag

2020-03-11 20:32 UTC, alexandrelafleur requested changes

2020-03-11 20:32 UTC, alexandrelafleur commented on main.py
> +
extra space

2020-03-11 20:32 UTC, alexandrelafleur commented on positions.py
> +    @return: array of delta positions ofxstep 2 joints for each of the 4 feet from walk sequence
missing space

2020-03-11 20:32 UTC, alexandrelafleur commented on positions.py
> +            angle0, angle1 = inverse_kinematic(leg[1], leg[0], 70, 100)
Add comment to explain what you are doing please

2020-03-11 20:32 UTC, alexandrelafleur commented on positions.py
> +    #initial positions
missing space after #

2020-04-01 11:54 UTC, alexandrelafleur approved these changes

2020-04-08 21:02 UTC, merged